/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatsRouteImport } from './routes/chats'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as HomeRouteImport } from './routes/home'
import { Route as IntroRouteImport } from './routes/intro'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MeRouteImport } from './routes/me'
import { Route as PrefsRouteImport } from './routes/prefs'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TicketRouteImport } from './routes/ticket'
import { Route as ChatIdRouteImport } from './routes/chat.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsRoute = ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IntroRoute = IntroRouteImport.update({
  id: '/intro',
  path: '/intro',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const PrefsRoute = PrefsRouteImport.update({
  id: '/prefs',
  path: '/prefs',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketRoute = TicketRouteImport.update({
  id: '/ticket',
  path: '/ticket',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chats': typeof ChatsRoute
  '/feedback': typeof FeedbackRoute
  '/home': typeof HomeRoute
  '/intro': typeof IntroRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/prefs': typeof PrefsRoute
  '/privacy': typeof PrivacyRoute
  '/requests': typeof RequestsRoute
  '/schedule': typeof ScheduleRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/ticket': typeof TicketRoute
  '/chat/$id': typeof ChatIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chats': typeof ChatsRoute
  '/feedback': typeof FeedbackRoute
  '/home': typeof HomeRoute
  '/intro': typeof IntroRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/prefs': typeof PrefsRoute
  '/privacy': typeof PrivacyRoute
  '/requests': typeof RequestsRoute
  '/schedule': typeof ScheduleRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/ticket': typeof TicketRoute
  '/chat/$id': typeof ChatIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chats': typeof ChatsRoute
  '/feedback': typeof FeedbackRoute
  '/home': typeof HomeRoute
  '/intro': typeof IntroRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/prefs': typeof PrefsRoute
  '/privacy': typeof PrivacyRoute
  '/requests': typeof RequestsRoute
  '/schedule': typeof ScheduleRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/ticket': typeof TicketRoute
  '/chat/$id': typeof ChatIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chats'
    | '/feedback'
    | '/home'
    | '/intro'
    | '/login'
    | '/me'
    | '/prefs'
    | '/privacy'
    | '/requests'
    | '/schedule'
    | '/signup'
    | '/terms'
    | '/ticket'
    | '/chat/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chats'
    | '/feedback'
    | '/home'
    | '/intro'
    | '/login'
    | '/me'
    | '/prefs'
    | '/privacy'
    | '/requests'
    | '/schedule'
    | '/signup'
    | '/terms'
    | '/ticket'
    | '/chat/$id'
  id:
    | '__root__'
    | '/'
    | '/chats'
    | '/feedback'
    | '/home'
    | '/intro'
    | '/login'
    | '/me'
    | '/prefs'
    | '/privacy'
    | '/requests'
    | '/schedule'
    | '/signup'
    | '/terms'
    | '/ticket'
    | '/chat/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatsRoute: typeof ChatsRoute
  FeedbackRoute: typeof FeedbackRoute
  HomeRoute: typeof HomeRoute
  IntroRoute: typeof IntroRoute
  LoginRoute: typeof LoginRoute
  MeRoute: typeof MeRoute
  PrefsRoute: typeof PrefsRoute
  PrivacyRoute: typeof PrivacyRoute
  RequestsRoute: typeof RequestsRoute
  ScheduleRoute: typeof ScheduleRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  TicketRoute: typeof TicketRoute
  ChatIdRoute: typeof ChatIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intro': {
      id: '/intro'
      path: '/intro'
      fullPath: '/intro'
      preLoaderRoute: typeof IntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prefs': {
      id: '/prefs'
      path: '/prefs'
      fullPath: '/prefs'
      preLoaderRoute: typeof PrefsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket': {
      id: '/ticket'
      path: '/ticket'
      fullPath: '/ticket'
      preLoaderRoute: typeof TicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$id': {
      id: '/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatsRoute: ChatsRoute,
  FeedbackRoute: FeedbackRoute,
  HomeRoute: HomeRoute,
  IntroRoute: IntroRoute,
  LoginRoute: LoginRoute,
  MeRoute: MeRoute,
  PrefsRoute: PrefsRoute,
  PrivacyRoute: PrivacyRoute,
  RequestsRoute: RequestsRoute,
  ScheduleRoute: ScheduleRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  TicketRoute: TicketRoute,
  ChatIdRoute: ChatIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
