/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatsRouteImport } from './routes/chats'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as HomeRouteImport } from './routes/home'
import { Route as IntroRouteImport } from './routes/intro'
import { Route as MeRouteImport } from './routes/me'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PrefsRouteImport } from './routes/prefs'
import { Route as TicketRouteImport } from './routes/ticket'
import { Route as ChatIdRouteImport } from './routes/chat.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsRoute = ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IntroRoute = IntroRouteImport.update({
  id: '/intro',
  path: '/intro',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PrefsRoute = PrefsRouteImport.update({
  id: '/prefs',
  path: '/prefs',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketRoute = TicketRouteImport.update({
  id: '/ticket',
  path: '/ticket',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chats': typeof ChatsRoute
  '/feedback': typeof FeedbackRoute
  '/home': typeof HomeRoute
  '/intro': typeof IntroRoute
  '/me': typeof MeRoute
  '/onboarding': typeof OnboardingRoute
  '/prefs': typeof PrefsRoute
  '/ticket': typeof TicketRoute
  '/chat/$id': typeof ChatIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chats': typeof ChatsRoute
  '/feedback': typeof FeedbackRoute
  '/home': typeof HomeRoute
  '/intro': typeof IntroRoute
  '/me': typeof MeRoute
  '/onboarding': typeof OnboardingRoute
  '/prefs': typeof PrefsRoute
  '/ticket': typeof TicketRoute
  '/chat/$id': typeof ChatIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chats': typeof ChatsRoute
  '/feedback': typeof FeedbackRoute
  '/home': typeof HomeRoute
  '/intro': typeof IntroRoute
  '/me': typeof MeRoute
  '/onboarding': typeof OnboardingRoute
  '/prefs': typeof PrefsRoute
  '/ticket': typeof TicketRoute
  '/chat/$id': typeof ChatIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chats'
    | '/feedback'
    | '/home'
    | '/intro'
    | '/me'
    | '/onboarding'
    | '/prefs'
    | '/ticket'
    | '/chat/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chats'
    | '/feedback'
    | '/home'
    | '/intro'
    | '/me'
    | '/onboarding'
    | '/prefs'
    | '/ticket'
    | '/chat/$id'
  id:
    | '__root__'
    | '/'
    | '/chats'
    | '/feedback'
    | '/home'
    | '/intro'
    | '/me'
    | '/onboarding'
    | '/prefs'
    | '/ticket'
    | '/chat/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatsRoute: typeof ChatsRoute
  FeedbackRoute: typeof FeedbackRoute
  HomeRoute: typeof HomeRoute
  IntroRoute: typeof IntroRoute
  MeRoute: typeof MeRoute
  OnboardingRoute: typeof OnboardingRoute
  PrefsRoute: typeof PrefsRoute
  TicketRoute: typeof TicketRoute
  ChatIdRoute: typeof ChatIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intro': {
      id: '/intro'
      path: '/intro'
      fullPath: '/intro'
      preLoaderRoute: typeof IntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prefs': {
      id: '/prefs'
      path: '/prefs'
      fullPath: '/prefs'
      preLoaderRoute: typeof PrefsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket': {
      id: '/ticket'
      path: '/ticket'
      fullPath: '/ticket'
      preLoaderRoute: typeof TicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$id': {
      id: '/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatsRoute: ChatsRoute,
  FeedbackRoute: FeedbackRoute,
  HomeRoute: HomeRoute,
  IntroRoute: IntroRoute,
  MeRoute: MeRoute,
  OnboardingRoute: OnboardingRoute,
  PrefsRoute: PrefsRoute,
  TicketRoute: TicketRoute,
  ChatIdRoute: ChatIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
